<?php

namespace ContainerXOpx27t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneratePostsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GeneratePostsCommand' shared autowired service.
     *
     * @return \App\Command\GeneratePostsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GeneratePostsCommand.php';

        $container->privates['App\\Command\\GeneratePostsCommand'] = $instance = new \App\Command\GeneratePostsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:generate-posts');
        $instance->setDescription('Add 100 records of posts');

        return $instance;
    }
}
