<?php

namespace ContainerXOpx27t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneratePostsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\GeneratePostsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\GeneratePostsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:generate-posts', [], 'Add 100 records of posts', false, #[\Closure(name: 'App\\Command\\GeneratePostsCommand')] fn (): \App\Command\GeneratePostsCommand => ($container->privates['App\\Command\\GeneratePostsCommand'] ?? $container->load('getGeneratePostsCommandService')));
    }
}
