<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXOpx27t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXOpx27t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXOpx27t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXOpx27t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXOpx27t\App_KernelDevDebugContainer([
    'container.build_hash' => 'XOpx27t',
    'container.build_id' => '95943b71',
    'container.build_time' => 1691667182,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXOpx27t');
